export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

export const RESET_ERRORS = 'RESET_ERRORS'
export const SET_ERROR = 'SET_ERROR'

export const UPDATE_USER = 'UPDATE_USER'
export const REFRESH_USER = 'REFRESH_USER'
export const SET_JOBS = 'SET_JOBS'
export const REVERT_SET_JOBS = 'REVERT_SET_JOBS'
export const SET_SUGGESTED_JOBS = 'SET_SUGGESTED_JOBS'
export const RESET_SUGGESTED_JOBS = 'RESET_SUGGESTED_JOBS'
export const SET_USERS = 'SET_USERS'
export const SET_DISPLAYED_USERS = 'SET_DISPLAYED_USERS'
export const EDITING_JOB = 'EDITING_JOB'
export const SET_USER_ADMINS = 'SET_USER_ADMINS'
export const DELETE_REJECTED = 'DELETE_REJECTED'

export const SET_BROWSER = 'SET_BROWSER'

export const ADD_FEEDBACK = 'ADD_FEEDBACK'
export const ADDED_SUCCESS = 'ADDED_SUCCESS'
export const RESET_FEEDBACK_SUCCESS = 'RESET_FEEDBACK_SUCCESS'

export const ADD_MESSAGE = 'ADD_MESSAGE'
export const RESET_MESSAGE = 'RESET_MESSAGE'
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE'
export const REMOVE_OLDEST_MESSAGE = 'REMOVE_OLDEST_MESSAGE'

export const UPDATE_CONTENT = 'UPDATE_CONTENT'

export const SET_PDF_URL = 'SET_PDF_URL'

export const SET_SHOW_PROFILE_COMPLETENESS_POPUP = 'SET_SHOW_PROFILE_COMPLETENESS_POPUP'

export const SET_CATEGORIES = 'SET_CATEGORIES'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'

export const SET_EVENTS = 'SET_EVENTS'
export const SET_UPDATED_EVENT = 'SET_UPDATED_EVENT'
export const DELETE_EVENT = 'DELETE_EVENT'
